DROP TABLE IF EXISTS PERSISTENT_LOGINS;
DROP TABLE IF EXISTS AUTHORITIES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS ROLES CASCADE;
DROP TABLE IF EXISTS GROUP_MEMBERS CASCADE;
DROP TABLE IF EXISTS GROUP_AUTHORITIES CASCADE;
DROP TABLE IF EXISTS `GROUPS` CASCADE;
