server:
  port: 9000
  tomcat:
    max-swallow-size: 100MB
#  servlet:

#    context-path: /test
#    encoding:
#      charset: utf-8
#      enabled: true
#      force: true

######################## 自定义配置  双@@中间是引用pom文件 ###################
app:
  encoding: "@project.build.sourceEncoding@"
  java:
    version: "@java.version@"
init:
  flag:
    table:
      security: true  # 重置数据表
############################################

#logging:
#  file:
#    path: "logs/"
#    name: "LearningSpringBootApplicationLogFile.log"
#  level:
#    root: debug
#   org.springframework.web: "debug"

############################### SPRING ###################################
spring:
  ###################### WEB #####################
  web:
    resources:
      cache:
        period: 31556926 # 一年

  ###################### DATASOURCE #####################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice?useUnicode=true&allowPublicKeyRetrieval=true&CharacterEncoding=utf8&useSSL=true
    username: root
    password: 123456

  ###################### 启动配置 #####################
  main:
    banner-mode: "console"
    lazy-initialization: true # 懒加载-Bean在需要时被创建，而不是在应用程序启动时就创建

  ###################### MULTIPART #####################
  servlet:
    multipart:
      enabled: true
#      location: C:/Users/admin/Desktop/file
      max-file-size: 10MB
      max-request-size: 2MB
      resolve-lazily: true
#      file-size-threshold: 1


###################### Mybatis-Plus #####################
mybatis-plus:
  global-config:
    banner: true
    db-config:
      id-type: assign_uuid # 主键策略
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # sql打印


