server:
  port: 9000
#  servlet:

#    context-path: /test
#    encoding:
#      charset: utf-8
#      enabled: true
#      force: true

######################## 自定义配置  双@@中间是引用pom文件 ###################
app:
  encoding: "@project.build.sourceEncoding@"
  java:
    version: "@java.version@"
init:
  flag:
    table:
      security: true  # 重置数据表
############################################

#logging:
#  file:
#    path: "logs/"
#    name: "LearningSpringBootApplicationLogFile.log"
#  level:
#    root: debug
#   org.springframework.web: "debug"

############################### SPRING ###################################
spring:
  ###################### WEB #####################
  web:
    resources:
      cache:
        period: 31556926 # 一年

  ###################### DATASOURCE #####################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice?useUnicode=true&allowPublicKeyRetrieval=true&CharacterEncoding=utf8&useSSL=true
    username: root
    password: 123456

  ###################### 启动配置 #####################
  main:
    banner-mode: "console"
    lazy-initialization: true # 懒加载-Bean在需要时被创建，而不是在应用程序启动时就创建

  ###################### MULTIPART #####################
  servlet:
    multipart:
      enabled: true
#      location: C:/Users/admin/Desktop/file
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false
#      file-size-threshold: 1

