CREATE TABLE USERS (
                       USERNAME VARCHAR(128) PRIMARY KEY,
                       PASSWORD VARCHAR(128) NOT NULL,
                       ENABLED TINYINT(1) NOT null
);

CREATE TABLE AUTHORITIES (
                             USERNAME VARCHAR(128) NOT NULL,
                             AUTHORITY VARCHAR(128) NOT NULL
);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (USERNAME, AUTHORITY);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK1 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME);