CREATE TABLE USERS (
    USERNAME VARCHAR(128) PRIMARY KEY,
    PASSWORD VARCHAR(128) NOT NULL,
    ENABLED TINYINT(1) NOT null
);

CREATE TABLE AUTHORITIES (
    USERNAME VARCHAR(128) NOT NULL,
    AUTHORITY VARCHAR(128) NOT NULL
);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (USERNAME, AUTHORITY);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK1 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME);

CREATE TABLE ROLES (
    AUTHORITY VARCHAR(128) PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL
);
INSERT INTO ROLES (AUTHORITY, NAME)  VALUES ('ROLE_ADMIN', '管理员');
INSERT INTO ROLES (AUTHORITY, NAME)  VALUES ('ROLE_USER', '用户');
INSERT INTO ROLES (AUTHORITY, NAME)  VALUES ('ROLE_TEST', '测试');


CREATE TABLE `GROUPS` (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    GROUP_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE GROUP_AUTHORITIES (
    GROUP_ID BIGINT NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    FOREIGN KEY (GROUP_ID) REFERENCES `GROUPS`(ID)
);

CREATE TABLE GROUP_MEMBERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    GROUP_ID BIGINT NOT NULL,
    FOREIGN KEY (GROUP_ID) REFERENCES `GROUPS`(ID)
);